require 'mustache'

module OSC
  module VNC
    # Provides a view for a variety of connection information templates in
    # templates/conn. Extra options can be passed to this view and accessed
    # directly in the mustache templates.
    class ConnView < Mustache
      self.template_path = CONN_TEMPLATE_PATH

      # @return [Session] the session object with connection information
      attr_reader :session

      # @return [String] the host specified in the VNC connection information
      attr_reader :host

      # @return [String] the port specified in the VNC connection information
      attr_reader :port

      # @return [String] the display port specified in the VNC connection information
      attr_reader :display

      # @return [String] the password specified in the VNC connection information
      attr_reader :password

      # @param [Hash] args the arguments used to construct a connection information view.
      # @option args [Session] :session The session object with the connection information
      def initialize(args)
        @session = args[:session]
        refresh
      end

      # @!method render(format, context = {})
      #   Generates a string from a template depending on the format name,
      #   current options include (:jnlp, :awesim, :terminal, :txt, :vnc,
      #   :yaml) (see templates/conn/*.mustache).
      #   @param [Symbol] format the format the connection info will be displayed in
      #   @param [Hash] context the context to be applied to mustache template
      #   @return [String] the mustache generated view of the template

      # The user to use for the ssh connection.
      # @return [String] the current user
      def sshuser
        ENV['USER']
      end

      # The host to use for the ssh connection.
      # @return [String] the hostname for the login node
      def sshhost
        "#{session.batch.cluster}.osc.edu"
      end

      # Get connection info from file generated by PBS batch job (read
      # template/script/vnc.mustache).
      #
      # @return [ConnView] the connection view object
      # @raise [InvalidPath] if connection file does not exist
      # @raise [InvalidConnInfo] if connection file doesn't contain required information (i.e.: host, port, display, password)
      def refresh
        _get_file_contents(session.conn_file)
        self
      end

      # Check if the method call exists in @session.script_view and run it.
      #
      # @param method_name the method name called
      # @param arguments the arguments to the call
      # @param block an optional block for the call
      def method_missing(method_name, *arguments, &block)
        if @session.script_view.respond_to? method_name
          @session.script_view.send method_name
        else
          super
        end
      end

      # Checks if the method responds to an instance method, or is able to
      # proxy it to @session.script_view.
      #
      # @param method_name the method name to check
      # @return [Boolean]
      def respond_to_missing?(method_name, include_private = false)
        @session.script_view.respond_to?(method_name) || super
      end


      private

      # Get connection information from a file.
      def _get_file_contents(file)
        raise InvalidPath, "connection file doesn't exist" unless File.file?(file)
        _parse File.read(file)
      end

      # Parse out connection info from a string.
      def _parse(string)
        {:@host => 'Host', :@port => 'Port', :@display => 'Display', :@password => 'Pass'}.each do |key, value|
          match = /^#{value}: (.*)$/.match(string)
          raise InvalidConnInfo, "#{key} not specified by batch job" unless match
          instance_variable_set(key, match[1].empty? ? nil : match[1])
        end
      end
    end
  end
end
