# Extra batch server options

glenn:
    :batch_type: compute
    :multicluster: false
oakley:
    :batch_type: compute
    :multicluster: false
ruby:
    :batch_type: compute
    :multicluster: false
oxymoron:
    :batch_type: shared
    :multicluster: true
