compute:
    glenn:  opt-batch.osc.edu
    oakley: oak-batch.osc.edu
    ruby:   ruby-batch.osc.edu

oxymoron:
    glenn:  oak-batch.osc.edu:17001
    oakley: oak-batch.osc.edu:17001
    ruby:   oak-batch.osc.edu:17001
