vnc:
  default: &DEFAULT_VNC
    name: 'vnc'
    geom: '800x600'
    dpi: 96
    idletimeout: 0
    extra_args: null
    otp?: false
    vncauth?: true
    pam?: false
    ssh_tunnel?: true
    tcp_server?: false
    novnc?: false
    cluster:
      oakley:
        fonts: '/usr/share/X11/fonts/misc,/usr/share/X11/fonts/75dpi,/usr/share/X11/fonts/100dpi,/usr/share/X11/fonts/Type1,/usr/share/fonts/default/Type1'
        load_turbovnc: |
          module load turbovnc/2.0
        novnc_launcher: '/usr/local/novnc/utils/launch.sh'
      ruby:
        fonts: '/usr/share/X11/fonts/misc,/usr/share/X11/fonts/100dpi,/usr/share/X11/fonts/Type1,/usr/share/fonts/default/Type1'
        load_turbovnc: |
          module load turbovnc/2.0
        novnc_launcher: '/usr/local/novnc/utils/launch.sh'
  shared:
    <<: *DEFAULT_VNC
    idletimeout: 300
    tcp_server?: true

server:
  default: &DEFAULT_SERVER
    ssh_tunnel?: true
    tcp_server?: false
