# Cluster specific options
# to be merged with the view depending on cluster chosen

glenn:
    fonts: /usr/share/X11/fonts/misc,/usr/share/X11/fonts/75dpi,/usr/share/X11/fonts/100dpi,/usr/share/X11/fonts/Type1,/usr/share/fonts/default/Type1
    load_turbovnc: |
        module load turbovnc-1.2

oakley:
    fonts: /usr/share/X11/fonts/misc,/usr/share/X11/fonts/75dpi,/usr/share/X11/fonts/100dpi,/usr/share/X11/fonts/Type1,/usr/share/fonts/default/Type1
    load_turbovnc: |
        module use /nfs/gpfs/PZS0645/local-oakley/share/modulefiles
        module load turbovnc/1.2.90

ruby:
    fonts: /usr/share/X11/fonts/misc,/usr/share/X11/fonts/100dpi,/usr/share/X11/fonts/Type1,/usr/share/fonts/default/Type1
    load_turbovnc: |
        module use /nfs/gpfs/PZS0645/local-ruby/share/modulefiles
        module load turbovnc/1.2.90
