#!/bin/bash

# Get directory this script is called in
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Change background wallpaper and center it
gconftool-2 -t str -s /desktop/gnome/background/picture_filename $DIR/images/TS_LOGO.jpg
gconftool-2 -t str -s /desktop/gnome/background/picture_options centered

# Set background color to white
gconftool-2 -t str -s /desktop/gnome/background/color_shading_type solid
gconftool-2 -t str -s /desktop/gnome/background/primary_color \#ffffff

# Add new menus
cp $DIR/config/menus/applications.menu $HOME/.config/menus/.
cp $DIR/config/menus/settings.menu $HOME/.config/menus/.

exec /etc/X11/xinit/xinitrc

vncserver -kill $DISPLAY
