#!/bin/bash

XDIR=${XDIR} /usr/bin/fvwm -f ${XDIR}/fvwm/fvwmrc &

if [ "${CLUSTER}" == "glenn" ]; then
  . /etc/profile.d/modules-env.sh
  module load VirtualGL-2.3
  module load paraview-3.8.0
elif [ "${CLUSTER}" == "oakley" ]; then
  . /etc/profile.d/lmod.sh
  module load virtualgl/2.3
  module load paraview/3.14.1
fi

vglrun paraview

vncserver -kill $DISPLAY
